# Generated by Django 3.2.5 on 2021-08-29 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCustomer',
            fields=[
                ('customerid', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ModelDesigns',
            fields=[
                ('did', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(default=None, null=True, upload_to='home/images/')),
                ('custid', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.modelcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCompany',
            fields=[
                ('companyid', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=150)),
                ('zipcode', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('custid', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.modelcustomer')),
            ],
        ),
    ]
