# Generated by Django 3.2.5 on 2021-09-03 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('tid', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='modeldesigns',
            name='ispaid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='modeldesigns',
            name='orderid',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='modeldesigns',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='modeldesigns',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.modeltype'),
        ),
    ]
