# Generated by Django 3.2.5 on 2021-09-04 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210903_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcompany',
            name='custid',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.modelcustomer'),
        ),
    ]
